name = "Performance"
uuid = "f99f42b8-f1d0-40fe-9dc3-6a6961ec8c82"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"

[compat]
BenchmarkTools = "1"
Cthulhu = "2.8"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
